# Generated by Django 4.2.2 on 2023-07-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombrar', max_length=300, verbose_name='nombre')),
                ('descripcion', models.CharField(default='Sin especificar', max_length=300, verbose_name='descripcion')),
                ('precio', models.IntegerField(default=0, verbose_name='precio')),
                ('estatus', models.BooleanField(verbose_name='estatus')),
            ],
        ),
    ]
