# Generated by Django 4.2.2 on 2023-07-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Productos', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_registro',
            field=models.IntegerField(default=2023, verbose_name='fecha_registro'),
        ),
    ]
