# Generated by Django 4.2.2 on 2023-07-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productos_options_productos_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha_registro',
            field=models.DateField(verbose_name='fecha_registro'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='precio'),
        ),
    ]
